# Copyright Business Blockchain www.blockchainempresarial.com. All Rights Reserved.
# Autor: Ricardo Ruano, ricardo@blockchainempresarial.com
# Date: 20-08-2020
# SPDX-License-Identifier: Apache-2.0
#
---
    ################################################################################
    #   Section: Organizations
    ################################################################################
    Organizations:
    
        - &FasilOrdererOrg
            Name: FasilOrdererOrg
            ID: FasilOrdererOrgMSP
            MSPDir: crypto-config/ordererOrganizations/esfasil.com/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('FasilOrdererOrgMSP.member')"
                Writers:
                    Type: Signature
                    Rule: "OR('FasilOrdererOrgMSP.member')"
                Admins:
                    Type: Signature
                    Rule: "OR('FasilOrdererOrgMSP.admin')"
            OrdererEndpoints:
                - orderer.esfasil.com:7050
    
        - &FasilOrg
            Name: FasilOrg
            ID: FasilOrgMSP
            MSPDir: crypto-config/peerOrganizations/org1.esfasil.com/msp
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('FasilOrgMSP.admin', 'FasilOrgMSP.peer', 'FasilOrgMSP.client')"
                Writers:
                    Type: Signature
                    Rule: "OR('FasilOrgMSP.admin', 'FasilOrgMSP.client')"
                Admins:
                    Type: Signature
                    Rule: "OR('FasilOrgMSP.admin')"
                Endorsement:
                    Type: Signature
                    Rule: "OR('FasilOrgMSP.peer')"
            AnchorPeers:
                - Host: peer0.org1.esfasil.com
                  Port: 7051
    ################################################################################
    #   SECTION: Capabilities
    ################################################################################
    Capabilities:
        Channel: &ChannelCapabilities
            V2_0: true
    
        Orderer: &OrdererCapabilities
            V2_0: true
    
        Application: &ApplicationCapabilities
            V2_0: true        
    
    ################################################################################
    #   SECTION: Application
    ################################################################################
    Application: &ApplicationDefaults
    
        # Organizations is the list of orgs which are defined as participants on
        # the application side of the network
        Organizations:
    
        # Policies defines the set of policies at this level of the config tree
        # For Application policies, their canonical path is
        #   /Channel/Application/<PolicyName>
        Policies:
            Readers:
                Type: ImplicitMeta
                Rule: "ANY Readers"
            Writers:
                Type: ImplicitMeta
                Rule: "ANY Writers"
            Admins:
                Type: ImplicitMeta
                Rule: "MAJORITY Admins"
            LifecycleEndorsement:
                Type: ImplicitMeta
                Rule: "MAJORITY Endorsement"
            Endorsement:
                Type: ImplicitMeta
                Rule: "MAJORITY Endorsement"
    
        Capabilities:
            <<: *ApplicationCapabilities    
    
    ################################################################################
    #   SECTION: Orderer
    ################################################################################
    Orderer: &OrdererDefaults
        # Orderer Type: The orderer implementation to start
        OrdererType: solo
    
    #    OrdererType: etcdraft
    
        EtcdRaft:
            Consenters:
            - Host: orderer.esfasil.com
              Port: 7050
              ClientTLSCert: ../organizations/ordererOrganizations/esfasil.com/orderers/orderer.esfasil.com/tls/server.crt
              ServerTLSCert: ../organizations/ordererOrganizations/esfasil.com/orderers/orderer.esfasil.com/tls/server.crt
    
        Addresses:
            - orderer.esfasil.com:7050
        BatchTimeout: 2s
        BatchSize:
            MaxMessageCount: 10
            AbsoluteMaxBytes: 99 MB
            PreferredMaxBytes: 512 KB
    
        Kafka:
            Brokers:
                - 127.0.0.1:9092
        Organizations:
    
        Policies:
            Readers:
                Type: ImplicitMeta
                Rule: "ANY Readers"
            Writers:
                Type: ImplicitMeta
                Rule: "ANY Writers"
            Admins:
                Type: ImplicitMeta
                Rule: "MAJORITY Admins"
            # BlockValidation specifies what signatures must be included in the block
            # from the orderer for the peer to validate it.
            BlockValidation:
                Type: ImplicitMeta
                Rule: "ANY Writers"
    
    ################################################################################
    #
    #   CHANNEL
    #
    #   This section defines the values to encode into a config transaction or
    #   genesis block for channel related parameters.
    #
    ################################################################################
    Channel: &ChannelDefaults
        # Policies defines the set of policies at this level of the config tree
        # For Channel policies, their canonical path is
        #   /Channel/<PolicyName>
        Policies:
            # Who may invoke the 'Deliver' API
            Readers:
                Type: ImplicitMeta
                Rule: "ANY Readers"
            # Who may invoke the 'Broadcast' API
            Writers:
                Type: ImplicitMeta
                Rule: "ANY Writers"
            # By default, who may modify elements at this config level
            Admins:
                Type: ImplicitMeta
                Rule: "MAJORITY Admins"
    
        # Capabilities describes the channel level capabilities, see the
        # dedicated Capabilities section elsewhere in this file for a full
        # description
        Capabilities:
            <<: *ChannelCapabilities
    
    ################################################################################
    #   Profile
    ################################################################################
    Profiles:
    
        FasilOrdererGenesis:
            <<: *ChannelDefaults
            Orderer:
                <<: *OrdererDefaults
                Organizations:
                    - *FasilOrdererOrg
                Capabilities:
                    <<: *OrdererCapabilities
            Consortiums:
                FasilConsortium:
                    Organizations:
                        - *FasilOrg
        FasilChannel:
            Consortium: FasilConsortium
            <<: *ChannelDefaults
            Application:
                <<: *ApplicationDefaults
                Organizations:
                    - *FasilOrg
                Capabilities:
                    <<: *ApplicationCapabilities
    