# Copyright Business Blockchain www.blockchainempresarial.com. All Rights Reserved.
# Autor: Ricardo Ruano, ricardo@blockchainempresarial.com
# Date: 20-08-2020
# SPDX-License-Identifier: Apache-2.0
#
OrdererOrgs:
    - Name: FasilOrderer
      Domain: esfasil.com
      EnableNodeOUs: true
      Specs:
        - Hostname: orderer
          SANS:
            - localhost
PeerOrgs:
    - Name: FasilOrg
      Domain: org1.esfasil.com
      EnableNodeOUs: true
      Template:
        Count: 1
        SANS:
          - localhost
      Users:
        Count: 1